name: C/C++ CI

on:
  push:
    branches: [ "main", "meson_action" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Meson Build
      uses: BSFishy/meson-build@v1.0.3
